// Generated by Selenium IDE
package org.ual.hmis.equipo18;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreartareaokTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void creartareaok() {
    // Test name: crear-tarea-ok
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://msdocs-node-mongo-2023-deianp189.azurewebsites.net/");
    // 2 | setWindowSize | 970x1037 | 
    driver.manage().window().setSize(new Dimension(970, 1037));
    // 3 | click | name=taskName | 
    driver.findElement(By.name("taskName")).click();
    // 4 | type | name=taskName | tarea1
    driver.findElement(By.name("taskName")).sendKeys("tarea1");
    // 5 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
